sequenceDiagram
    actor U as User
    participant M as manager_home.js
    participant PS as Project select
    participant B as Assign button
    participant SU as Success message
    participant E as Error message
    participant MH as ManagerHome
    participant S as Session
    participant PD as ProjectDAO


    U ->> M: assign button click
    M ->> MH: AJAX POST /manager-home?action=assignProject
    MH ->> S: getAttribute(user)
    S -->> MH: user
    MH ->> MH: get, trim and validate post parameters
    MH ->> PD: assignProject(project_id)

    MH -->> M: response
    alt success
    M ->> PS: render projects
    M ->> B: hide assign button
    M ->> SU: show success message
    else error
    M ->> E: show error message
    end





